[package]
name = "bksd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0"
tokio-rusqlite = "0.7.0"

